GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/id

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer <token>

 {
 "title": "test title"
 }

###
PUT http://localhost:3001/api/blogs/id
Content-Type: application/json
Authorization: Bearer <token>

{
  "likes": 18
}

###
DELETE http://localhost:3001/api/blogs/id
Authorization: Bearer <token>

